name: DEV TLOZ API

on:
  push:
    branches:
      - dev

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clone repository
        uses: actions/checkout@v2

      - name: 🐍 Python - Set up
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 🐍 Python - Instalando paquetes...
        run: |
          pip install -r requirements.txt
                
      - name: 🐍 Python - Ejecutando uvicorn en background
        run: |
          uvicorn app.main:app --reload &
          sleep 5

      - name: 🐍 PYTHON - 🧪 Ejecutando pytests... # Ejecuta los pytests
        run: |
          pytest -s -v --disable-warnings app/tests/test_main.py
        continue-on-error: true